# Generated by Django 3.1.1 on 2020-10-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('Phone_no', models.IntegerField(default='')),
                ('message', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
